/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

/**
 *
 * @author praktek
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        //this.setSize(1000, 600);
        setLocationRelativeTo(this);
        Koneksi.DataBase.KoneksiDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnLayerSuplier = new javax.swing.JButton();
        btnLayerBarang = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnLayerLapPenjualan = new javax.swing.JButton();
        btnLayerLapBarang = new javax.swing.JButton();
        btnLayerLapSuplier = new javax.swing.JButton();
        btnLayerBuktiPesan = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MMenu = new javax.swing.JMenu();
        MKategori = new javax.swing.JMenuItem();
        MBarang1 = new javax.swing.JMenuItem();
        MSuplier = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        TBuktiPesan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        LPelanggan = new javax.swing.JMenuItem();
        LBarang = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        Mexit = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistem Penjualan Al-Muslimin Collection");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Another day in Paradise", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Al-Muslimin Collection");

        jPanel2.setBackground(new java.awt.Color(204, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLayerSuplier.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLayerSuplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/joyent.png"))); // NOI18N
        btnLayerSuplier.setText("SUPLIER");
        btnLayerSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayerSuplierActionPerformed(evt);
            }
        });

        btnLayerBarang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLayerBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/joyent.png"))); // NOI18N
        btnLayerBarang.setText("BARANG");
        btnLayerBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayerBarangActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLayerLapPenjualan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLayerLapPenjualan.setText("LAPORAN PENDAPATAN");
        btnLayerLapPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayerLapPenjualanActionPerformed(evt);
            }
        });

        btnLayerLapBarang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLayerLapBarang.setText("LAPORAN STOK");
        btnLayerLapBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayerLapBarangActionPerformed(evt);
            }
        });

        btnLayerLapSuplier.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLayerLapSuplier.setText("LAPORAN SUPLIER");
        btnLayerLapSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayerLapSuplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLayerLapPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(btnLayerLapBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLayerLapSuplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(btnLayerLapPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLayerLapBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLayerLapSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btnLayerBuktiPesan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLayerBuktiPesan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buy.png"))); // NOI18N
        btnLayerBuktiPesan.setToolTipText("Buat Bukti Pesan");
        btnLayerBuktiPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayerBuktiPesanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLayerBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLayerSuplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLayerBuktiPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnLayerBuktiPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnLayerBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLayerSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        MMenu.setText("File Master");

        MKategori.setText("Entry Data Kategori");
        MKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MKategoriActionPerformed(evt);
            }
        });
        MMenu.add(MKategori);

        MBarang1.setText("Entry Data Barang");
        MBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBarang1ActionPerformed(evt);
            }
        });
        MMenu.add(MBarang1);

        MSuplier.setText("Entry Data Suplier");
        MMenu.add(MSuplier);

        MenuExit.setText("Exit");
        MenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuExitMouseClicked(evt);
            }
        });
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        MMenu.add(MenuExit);

        jMenuBar1.add(MMenu);

        jMenu2.setText("Transaksi");

        TBuktiPesan.setText("Bukti Pesan");
        TBuktiPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBuktiPesanActionPerformed(evt);
            }
        });
        jMenu2.add(TBuktiPesan);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");

        LPelanggan.setText("Laporan Pendapatan");
        LPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LPelangganActionPerformed(evt);
            }
        });
        jMenu3.add(LPelanggan);

        LBarang.setText("Laporan Data Barang");
        LBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LBarangActionPerformed(evt);
            }
        });
        jMenu3.add(LBarang);

        jMenuItem1.setText("Laporan Data Suplier");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        Mexit.setText("Exit");
        Mexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MexitMouseClicked(evt);
            }
        });
        jMenuBar1.add(Mexit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(603, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_MexitMouseClicked

    private void LPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LPelangganActionPerformed
        View.LapPendapatan P = new View.LapPendapatan();
         P.setVisible(true);   
         setLocationRelativeTo(this); 
         P.getTgl1().requestFocus();
    }//GEN-LAST:event_LPelangganActionPerformed

    private void LBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LBarangActionPerformed
        View.LapStok B = new View.LapStok();
        B.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_LBarangActionPerformed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuExitMouseClicked

    }//GEN-LAST:event_MenuExitMouseClicked

    private void MBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBarang1ActionPerformed
        View.MBarang B = new MBarang();
        B.setVisible(true);
        setLocationRelativeTo(this);
        B.getTxtnmbarang().requestFocus();
    }//GEN-LAST:event_MBarang1ActionPerformed

    private void MKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MKategoriActionPerformed
        View.MKategoriBarang k = new MKategoriBarang();
        k.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_MKategoriActionPerformed

    private void TBuktiPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBuktiPesanActionPerformed
        View.TBuktiPesan T = new View.TBuktiPesan();
         T.setVisible(true); 
         setLocationRelativeTo(this);
    }//GEN-LAST:event_TBuktiPesanActionPerformed

    private void btnLayerLapBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayerLapBarangActionPerformed
        View.LapStok B = new View.LapStok();
        B.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_btnLayerLapBarangActionPerformed

    private void btnLayerLapPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayerLapPenjualanActionPerformed
        View.LapPendapatan P = new View.LapPendapatan();
        P.setVisible(true);
        setLocationRelativeTo(this);
        P.getTgl1().requestFocus();
    }//GEN-LAST:event_btnLayerLapPenjualanActionPerformed

    private void btnLayerBuktiPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayerBuktiPesanActionPerformed
        View.TBuktiPesan T = new View.TBuktiPesan();
        T.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_btnLayerBuktiPesanActionPerformed

    private void btnLayerBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayerBarangActionPerformed
        View.MBarang B = new MBarang();
        B.setVisible(true);
        setLocationRelativeTo(this);
        B.getTxtnmbarang().requestFocus();
    }//GEN-LAST:event_btnLayerBarangActionPerformed

    private void btnLayerSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayerSuplierActionPerformed
        View.MSuplier S = new MSuplier();
        S.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_btnLayerSuplierActionPerformed

    private void btnLayerLapSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayerLapSuplierActionPerformed
        View.LapSuplier S = new LapSuplier();
        S.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_btnLayerLapSuplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LBarang;
    private javax.swing.JMenuItem LPelanggan;
    private javax.swing.JMenuItem MBarang1;
    private javax.swing.JMenuItem MKategori;
    private javax.swing.JMenu MMenu;
    private javax.swing.JMenuItem MSuplier;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenu Mexit;
    private javax.swing.JMenuItem TBuktiPesan;
    private javax.swing.JButton btnLayerBarang;
    private javax.swing.JButton btnLayerBuktiPesan;
    private javax.swing.JButton btnLayerLapBarang;
    private javax.swing.JButton btnLayerLapPenjualan;
    private javax.swing.JButton btnLayerLapSuplier;
    private javax.swing.JButton btnLayerSuplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
